#pragma once
#include "core/Types.h"
#include "orderbook/Order.h"
#include <unordered_map>
#include <string>

// Per-agent, per-ticker account state.
struct PositionRecord {
    Qty   net_qty      = 0;  // signed: >0 long, <0 short, 0 flat
    Price cost_basis   = 0;  // |net_qty| × avg_entry_price in ticks (always >= 0)
    Price realized_pnl = 0;  // signed cumulative P&L in price-ticks × lots
    Price fees_net     = 0;  // signed: positive = fees paid, negative = rebates earned
};

class PositionLedger {
public:
    // Pre-populate an agent's position before simulation starts.
    void seed(AgentId agent, const std::string& ticker,
              Qty qty, Price avg_cost_per_lot);

    // Record one side of a fill.
    // Returns the realized P&L generated by this transaction (0 when extending).
    Price apply(AgentId agent, Side side, const std::string& ticker,
                Qty qty, Price exec_price, Price fee);

    // ── Queries ────────────────────────────────────────────────────────────
    Qty   net_qty      (AgentId agent, const std::string& ticker) const;
    Price avg_cost     (AgentId agent, const std::string& ticker) const;
    Price realized_pnl (AgentId agent, const std::string& ticker) const;
    Price fees_net     (AgentId agent, const std::string& ticker) const;

    // Unrealized P&L at a given mark price.
    Price unrealized_pnl(AgentId agent, const std::string& ticker,
                          Price mark_price) const;

    // Sum of all agents' net_qty for a ticker
    // (should equal total seeded qty — conservation invariant).
    Qty total_net_qty(const std::string& ticker) const;

    const PositionRecord* get(AgentId agent, const std::string& ticker) const;

    using TickerMap = std::unordered_map<std::string, PositionRecord>;
    const std::unordered_map<AgentId, TickerMap>& all() const { return positions_; }

private:
    std::unordered_map<AgentId, TickerMap> positions_;

    PositionRecord& get_or_create(AgentId agent, const std::string& ticker);
};
